package com.wojciechkula.deepskyapp.data.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.wojciechkula.deepskyapp.data.database.dao.FavouritePictureDao
import com.wojciechkula.deepskyapp.data.database.entity.FavouritePictureEntity

internal const val APOD_DATABASE_NAME = "apod_database.db"

@Database(entities = [FavouritePictureEntity::class], version = 2)
@ConstructedBy(APODDatabaseConstructor::class)
internal abstract class APODLocalDatabase : RoomDatabase() {
    abstract fun favouritePictureDao(): FavouritePictureDao
}

// The `actual` implementations are generated by the Room KSP processor per target.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
internal expect object APODDatabaseConstructor : RoomDatabaseConstructor<APODLocalDatabase> {
    override fun initialize(): APODLocalDatabase
}
