import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

// Resolution order for the APOD key: this checkout's local.properties, then a Gradle property, then
// an environment variable. Putting it in ~/.gradle/gradle.properties is the recommended spot — that
// file lives outside the repository, so every clone and every git worktree picks the key up
// automatically instead of needing its own local.properties (a worktree gets a fresh one with only
// sdk.dir). The key is resolved here rather than in :androidApp so that iOS, which cannot read a
// buildConfigField, reads exactly the same value.
val apodApiKey: String = (
    localProperties.getProperty("APOD_API_KEY")
        ?: providers.gradleProperty("APOD_API_KEY").orNull
        ?: providers.environmentVariable("APOD_API_KEY").orNull
    )?.trim()?.removeSurrounding("\"").orEmpty().ifBlank {
    logger.warn(
        "APOD_API_KEY is not set: the app will build but every APOD request will fail. " +
            "Add 'APOD_API_KEY=<key>' to ~/.gradle/gradle.properties so all worktrees inherit it."
    )
    ""
}

val generateApodApiKey by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/apodApiKey/kotlin")
    val key = apodApiKey.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
    inputs.property("apodApiKey", key)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().asFile.resolve("com/wojciechkula/deepskyapp/ApodApiKey.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.wojciechkula.deepskyapp

            // Generated by the :shared `generateApodApiKey` task — do not edit.
            internal object ApodApiKey {
                const val VALUE: String = "$key"
            }
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }
    
    androidLibrary {
       namespace = "com.wojciechkula.deepskyapp.shared"
       compileSdk = libs.versions.android.compileSdk.get().toInt()
       minSdk = libs.versions.android.minSdk.get().toInt()
    
       compilerOptions {
           jvmTarget = JvmTarget.JVM_11
       }
       // Required for the composeResources tab labels to be packaged into the Android artifact —
       // without it stringResource throws MissingResourceException on the first frame.
       androidResources {
           enable = true
       }
       withHostTest {}
    }
    
    sourceSets {
        commonMain { kotlin.srcDir(generateApodApiKey) }

        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.koin.android)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(projects.data)
            implementation(projects.core.common)
            implementation(projects.core.designsystem)
            implementation(projects.core.navigation)
            implementation(projects.feature.about)
            implementation(projects.feature.favourites)
            implementation(projects.feature.picture)
            implementation(libs.koin.core)
            implementation(libs.koin.composeViewmodel)
            implementation(libs.coil.compose)
            implementation(libs.coil.networkKtor3)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

// Pinned so the generated accessors keep a stable package regardless of the module coordinates. The
// only resources :shared owns are the bottom-bar tab labels, which belong here because deciding which
// destinations are tabs — and what they are called — is a presentation concern of the nav host.
compose.resources {
    packageOfResClass = "com.wojciechkula.deepskyapp.shared.resources"
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}