name: Android CI

on:
  push:
    branches:
      - "**"

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  # TODO: To uncomment later
  #  detekt:
  #    name: Run Detekt
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout repository
  #        uses: actions/checkout@v2
  #      - name: Set up JDK 17
  #        uses: actions/setup-java@v2
  #        with:
  #          java-version: '17'
  #          distribution: 'temurin'
  #          cache: gradle
  #      - name: Create local.properties
  #        run: echo "APOD_API_KEY=${{ secrets.APOD_API_KEY }}" > local.properties
  #
  #      - name: Run Detekt
  #        run: ./gradlew --no-daemon --build-cache detekt
  #      - name: Upload Detekt Results
  #        uses: actions/upload-artifact@v2
  #        if: always()
  #        with:
  #          name: detekt-report.html
  #          path: build/reports/detekt/detekt-report.html

  ktlint:
    name: Run ktLint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
#          cache: gradle
      - name: Create local.properties
        run: echo "APOD_API_KEY=${{ secrets.APOD_API_KEY }}" > local.properties

      - name: Run Lint
        run: ./gradlew --no-daemon --build-cache ktlint
      - name: Upload Lint Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ktlint-report.html
          path: build/reports/ktlint/ktlint-report.html

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
#          cache: gradle
      - name: Create local.properties
        run: echo "APOD_API_KEY=${{ secrets.APOD_API_KEY }}" > local.properties

      - name: Run Tests
        run: ./gradlew --no-daemon --build-cache test
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unitTest-report.html
          path: app/build/reports/tests/testDebugUnitTest/index.html
